version: "3.2"
services:

  mongodb:
    image: mongo:4
    networks:
      - superdesk
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  redis:
    image: redis:3
    networks:
      - superdesk
    ports:
      - "6379:6379"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - discovery.type=single-node
    networks:
      - superdesk
    ports:
      - "9200:9200"
    volumes:
      - elastic:/usr/share/elasticsearch/data

networks:
    superdesk:
        driver: bridge

volumes:
  mongo:
  elastic:
